blueprint:
  name: 'Remote based light control (MQTT)'
  description: 'Switch lights based on remote MQTT device triggers for three buttons and six lights'
  domain: automation
  input:
    mqtt_device:
      name: (Required) MQTT Device
      selector:
        device:
          integration: mqtt
    first_single_click:
      name: First button - single click
      default: []
      selector:
        entity:
          domain: light
    first_double_click:
      name: First button - double click
      default: []
      selector:
        entity:
          domain: light
    second_single_click:
      name: Second button - single click
      default: []
      selector:
        entity:
          domain: light
    second_double_click:
      name: Second button - double click
      default: []
      selector:
        entity:
          domain: light
    third_single_click:
      name: Third button - single click
      default: []
      selector:
        entity:
          domain: light
    third_double_click:
      name: Third button - double click
      default: []
      selector:
        entity:
          domain: light

# Automation schema
mode: restart
max_exceeded: silent

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: 1_single

  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: 1_double

  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: 2_single

  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: 2_double

  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: 3_single

  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: 3_double

action:
  - choose:
      - conditions:
          - "{{ trigger.payload == '1_single' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input first_single_click

      - conditions:
          - "{{ trigger.payload == '1_double' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input first_double_click

      - conditions:
          - "{{ trigger.payload == '2_single' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input second_single_click

      - conditions:
          - "{{ trigger.payload == '2_double' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input second_double_click

      - conditions:
          - "{{ trigger.payload == '3_single' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input third_single_click

      - conditions:
          - "{{ trigger.payload == '3_double' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input third_double_click
