blueprint:
  name: 'Switch follow remotly controlled light'
  description: 'Blueprint to control a switch  based on the light state.'
  domain: automation
  input:
    switch_entity:
      name: Wall Switch
      description: 'Select the switch correlated to the light'
      selector:
        entity:
          domain: switch
    light_entity:
      name: Light
      description: 'Select the light'
      selector:
        entity:
          domain: light
    delay_time:
      name: Delay (ms)
      description: 'Specify delay time in milliseconds before action is taken'
      default: 750
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: ms

trigger:
  - platform: device
    type: changed_states
    entity_id: !input light_entity
    domain: light

action:
  - delay:
      milliseconds: !input delay_time
  - choose:
      - conditions:
          - condition: device
            type: is_on
            entity_id: !input switch_entity
            domain: switch
          - condition: and
            conditions:
              - condition: device
                type: is_off
                entity_id: !input light_entity
                domain: light
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input switch_entity
      - conditions:
          - condition: device
            type: is_off
            entity_id: !input switch_entity
            domain: switch
          - condition: and
            conditions:
              - condition: device
                type: is_on
                entity_id: !input light_entity
                domain: light
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_entity

mode: single
