blueprint:
  name: 'Switch Follows Remotely Controlled Light'
  description: 'Blueprint to control a switch based on the light state.'
  domain: automation
  input:
    switch_entity:
      name: Wall Switch
      description: 'Select the switch correlated to the light'
      selector:
        entity:
          domain: switch
    light_entity:
      name: Light
      description: 'Select the light'
      selector:
        entity:
          domain: light
    delay_time:
      name: Delay (ms)
      description: 'Specify delay time in milliseconds before action is taken'
      default: 750
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: ms

trigger:
  - platform: state
    entity_id: !input light_entity

action:
  - delay:
      milliseconds: !input delay_time
  - choose:
      - conditions:
          - condition: state
            entity_id: !input switch_entity
            state: "on"
          - condition: state
            entity_id: !input light_entity
            state: "off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input switch_entity
      - conditions:
          - condition: state
            entity_id: !input switch_entity
            state: "off"
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_entity

mode: single
